### ISSUE TITLE
Only rendered blade files are checked

### ISSUE THREAD

**Issue by szepeviktor** [TomasVotruba/bladestan#2] opened 2023-03-04 19:09 UTC
From https://github.com/TomasVotruba/tomasvotruba.com/pull/1384#issuecomment-1454830723

I'm not sure. 

```neon
parameters:
    paths:
        - app/View/
    level: 0
    templatePaths:
        - resources/views/
```

with this configuration blade files are not checked.

```neon
parameters:
    paths:
        - resources/views/
    level: 0
    # phpstan for blade
    templatePaths:
        - resources/views/
```

this works.

**Comment by TomasVotruba** [comment] 2023-03-04 19:10
I have no idea how the package works now. I'll need a reproducer test case

**Comment by szepeviktor** [comment] 2023-03-04 19:11
May I contribute my default CI workflows?
They are very long but 3 years of maintenance is **included**.

**Comment by TomasVotruba** [comment] 2023-03-04 19:17
Give me a day or two to make CI pass first. I'm still rebooting package I've dperecated a year ago :) 

https://packagist.org/packages/symplify/template-phpstan-compiler

Come on Monday, that would be more useful for me :+1:

**Comment by szepeviktor** [comment] 2023-03-07 19:40
Got it! When used with `nunomaduro/larastan` Blade files are ignored.
Larastan makes Bladestan ignore them.

**Comment by TomasVotruba** [comment] 2023-03-07 23:13
That's not it.

The testing PR uses both larastan and bladestan: https://github.com/TomasVotruba/tomasvotruba.com/pull/1387

**Comment by szepeviktor** [comment] 2023-03-07 23:21
That PR does not set `templatePaths`, so only blade files in `view()` calls are checked.

**Comment by AJenbo** [comment] 2023-03-18 12:01
It might be good to look at how Larastan find `view-strings` and use a similar way to determin if it's a template that should be analyzed. From what I can see it looks like email templates are also not analyzed since they do not use `view()`, the same is true when a component uses `$this->view()` instead of `view()`.

**Comment by TomasVotruba** [comment] 2023-03-26 11:19
Closing as this is now mixing many various issues and getting messy :) 

To re-open, please provide reproducer first, even if Github repository :+1:

**Closed** 2023-03-26 11:19 UTC

**Comment by szepeviktor** [comment] 2023-03-26 11:21
> this is now mixing many various issues and getting messy :)

Yes!
