### ISSUE TITLE
Cache and false positive/negative results

### ISSUE THREAD

**Issue by fabio-ventura** [TomasVotruba/bladestan#103] opened 2024-08-02 09:08 UTC
Hi,
when I run phpstan, I get results that are not reliable.
To have reliable results I have to delete the cache files:

```
/tmp/*-blade-compiled.php
/tmp/cachegrind.out.*.gz
/tmp/phpstan
```
But I guess it's something inside `/tmp/phpstan`

This only happens for views.

**Comment by AJenbo** [comment] 2024-08-02 10:42
Duplicate of https://github.com/TomasVotruba/bladestan/issues/85 / https://github.com/TomasVotruba/bladestan/issues/69

**Closed by AJenbo** 2024-08-02 10:42 UTC
